# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pilot.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 994)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QToolTip\n"
"{\n"
"    border: 1px solid #76797C;\n"
"    background-color: rgb(90, 102, 117);;\n"
"    color: white;\n"
"    padding: 5px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    selection-background-color:#3daee9;\n"
"    selection-color: #eff0f1;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    border: 0px transparent black;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"QCheckBox\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: #eff0f1;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"    color: #76797C;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator\n"
"{\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"QGroupBox::indicator\n"
"{\n"
"    margin-left: 2px;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover,\n"
"QCheckBox::indicator:unchecked:focus,\n"
"QCheckBox::indicator:unchecked:pressed,\n"
"QGroupBox::indicator:unchecked:hover,\n"
"QGroupBox::indicator:unchecked:focus,\n"
"QGroupBox::indicator:unchecked:pressed\n"
"{\n"
"  border: none;\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_focus.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:focus,\n"
"QCheckBox::indicator:checked:pressed,\n"
"QGroupBox::indicator:checked:hover,\n"
"QGroupBox::indicator:checked:focus,\n"
"QGroupBox::indicator:checked:pressed\n"
"{\n"
"  border: none;\n"
"    image: url(:/qss_icons/rc/checkbox_checked_focus.png);\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:indeterminate\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_indeterminate.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate:focus,\n"
"QCheckBox::indicator:indeterminate:hover,\n"
"QCheckBox::indicator:indeterminate:pressed\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_indeterminate_focus.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:disabled,\n"
"QGroupBox::indicator:checked:disabled\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:disabled,\n"
"QGroupBox::indicator:unchecked:disabled\n"
"{\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"}\n"
"\n"
"QRadioButton\n"
"{\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: #eff0f1;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QRadioButton:disabled\n"
"{\n"
"    color: #76797C;\n"
"}\n"
"QRadioButton::indicator\n"
"{\n"
"    width: 21px;\n"
"    height: 21px;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked\n"
"{\n"
"    image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator:unchecked:hover,\n"
"QRadioButton::indicator:unchecked:focus,\n"
"QRadioButton::indicator:unchecked:pressed\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_unchecked_focus.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QRadioButton::indicator:checked:focus,\n"
"QRadioButton::indicator:checked:pressed\n"
"{\n"
"    border: none;\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked_focus.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled\n"
"{\n"
"    outline: none;\n"
"    image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked:disabled\n"
"{\n"
"    image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"}\n"
"\n"
"\n"
"QMenuBar\n"
"{\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    border: 1px solid #76797C;\n"
"    background-color: #3daee9;\n"
"    color: #eff0f1;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #76797C;\n"
"    color: #eff0f1;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QMenu::icon\n"
"{\n"
"    margin: 5px;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 5px 30px 5px 30px;\n"
"    margin-left: 5px;\n"
"    border: 1px solid transparent; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 2px;\n"
"    background: lightblue;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"/* non-exclusive indicator = check box style indicator\n"
"   (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    image: url(:/qss_icons/rc/checkbox_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/checkbox_checked_disabled.png);\n"
"}\n"
"\n"
"/* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"QMenu::indicator:exclusive:unchecked {\n"
"    image: url(:/qss_icons/rc/radio_unchecked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected {\n"
"    image: url(:/qss_icons/rc/radio_unchecked_disabled.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"    image: url(:/qss_icons/rc/radio_checked.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected {\n"
"    image: url(:/qss_icons/rc/radio_checked_disabled.png);\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"    margin: 5px;\n"
"    image: url(:/qss_icons/rc/right_arrow.png)\n"
"}\n"
"\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #454545;\n"
"    background-color: #31363b;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    alternate-background-color: #31363b;\n"
"    color: #eff0f1;\n"
"    border: 1px solid 3A3939;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QWidget:focus, QMenuBar:focus\n"
"{\n"
"    border: 1px solid #3daee9;\n"
"}\n"
"\n"
"QTabWidget:focus, QCheckBox:focus, QRadioButton:focus, QSlider:focus\n"
"{\n"
"    border: none;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: #232629;\n"
"    padding: 5px;\n"
"    border-style: solid;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border:1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    margin-top: 20px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"}\n"
"\n"
"QAbstractScrollArea\n"
"{\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"    background-color: #2A2929;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    margin: 0px 3px 0px 3px;\n"
"    border-image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,QScrollBar::add-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/right_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/left_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #2A2929;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #2A2929;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: #605F5F;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    margin: 3px 0px 3px 0px;\n"
"    border-image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,QScrollBar::sub-line:vertical:on\n"
"{\n"
"\n"
"    border-image: url(:/qss_icons/rc/up_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on\n"
"{\n"
"    border-image: url(:/qss_icons/rc/down_arrow.png);\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #232629;\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #232629;;\n"
"    color: #eff0f1;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: #76797C;\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QSizeGrip {\n"
"    image: url(:/qss_icons/rc/sizegrip.png);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: #31363b;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    spacing: 2px;\n"
"    border: 1px dashed #76797C;\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: #787876;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #76797C;\n"
"    spacing: 2px;\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 1px;\n"
"    background-color: #76797C;\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"\n"
"QFrame\n"
"{\n"
"    border-radius: 3px;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QFrame[frameShape=\"0\"]\n"
"{\n"
"    border-radius: 2px;\n"
"    border: 1px transparent #76797C;\n"
"}\n"
"\n"
"QStackedWidget\n"
"{\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBar {\n"
"    border: 1px transparent #393838;\n"
"    background: 1px solid #31363b;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    image: url(:/qss_icons/rc/Hmovetoolbar.png);\n"
"}\n"
"QToolBar::handle:vertical {\n"
"    image: url(:/qss_icons/rc/Vmovetoolbar.png);\n"
"}\n"
"QToolBar::separator:horizontal {\n"
"    image: url(:/qss_icons/rc/Hsepartoolbar.png);\n"
"}\n"
"QToolBar::separator:vertical {\n"
"    image: url(:/qss_icons/rc/Vsepartoolbar.png);\n"
"}\n"
"QToolButton#qt_toolbar_ext_button {\n"
"    background: #58595a\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: #31363b;\n"
"    border-width: 1px;\n"
"    border-color: #454545;\n"
"    border-style: solid;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 2px;\n"
"    color: #454545;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    background-color: #3daee9;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #3daee9;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #3daee9;\n"
"    border-style: solid;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 2px;\n"
"    padding: 5px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    background-color: #76797C;\n"
"    border-color: #6A6969;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover,QAbstractSpinBox:hover,QLineEdit:hover,QTextEdit:hover,QPlainTextEdit:hover,QAbstractView:hover,QTreeView:hover\n"
"{\n"
"    border: 1px solid #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #76797C;\n"
"    selection-background-color: #3daee9;\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on, QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"    color: #eff0f1;\n"
"    border-radius: 2px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button\n"
"{\n"
"    background-color: transparent;\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center left;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow,QAbstractSpinBox::up-arrow:disabled,QAbstractSpinBox::up-arrow:off {\n"
"    image: url(:/qss_icons/rc/up_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"QAbstractSpinBox::up-arrow:hover\n"
"{\n"
"    image: url(:/qss_icons/rc/up_arrow.png);\n"
"}\n"
"\n"
"\n"
"QAbstractSpinBox::down-arrow,QAbstractSpinBox::down-arrow:disabled,QAbstractSpinBox::down-arrow:off\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"QAbstractSpinBox::down-arrow:hover\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"    border: 0px solid black;\n"
"}\n"
"\n"
"QTabWidget{\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #76797C;\n"
"    padding: 5px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTabBar\n"
"{\n"
"    qproperty-drawBase: 0;\n"
"    left: 5px; /* move to the right by 5px */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTabBar:focus\n"
"{\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button  {\n"
"    image: url(:/qss_icons/rc/close.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:hover\n"
"{\n"
"    image: url(:/qss_icons/rc/close-hover.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    image: url(:/qss_icons/rc/close-pressed.png);\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* TOP TABS */\n"
"QTabBar::tab:top {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    min-width: 50px;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent black;\n"
"    border-top-left-radius: 2px;\n"
"    border-top-right-radius: 2px;    \n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"/* BOTTOM TABS */\n"
"QTabBar::tab:bottom {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-top: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-width: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-top: 1px transparent black;\n"
"    border-bottom-left-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"/* LEFT TABS */\n"
"QTabBar::tab:left {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-left: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-left: 1px transparent black;\n"
"    border-top-right-radius: 2px;\n"
"    border-bottom-right-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"\n"
"/* RIGHT TABS */\n"
"QTabBar::tab:right {\n"
"    color: #eff0f1;\n"
"    border: 1px solid #76797C;\n"
"    border-right: 1px transparent black;\n"
"    background-color: #31363b;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-left-radius: 2px;\n"
"    min-height: 50px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #54575B;\n"
"    border: 1px solid #76797C;\n"
"    border-right: 1px transparent black;\n"
"    border-top-left-radius: 2px;\n"
"    border-bottom-left-radius: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover {\n"
"    background-color: #3daee9;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"     image: url(:/qss_icons/rc/right_arrow.png);\n"
" }\n"
"\n"
" QTabBar QToolButton::left-arrow:enabled {\n"
"     image: url(:/qss_icons/rc/left_arrow.png);\n"
" }\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled {\n"
"     image: url(:/qss_icons/rc/right_arrow_disabled.png);\n"
" }\n"
"\n"
" QTabBar QToolButton::left-arrow:disabled {\n"
"     image: url(:/qss_icons/rc/left_arrow_disabled.png);\n"
" }\n"
"\n"
"\n"
"QDockWidget {\n"
"    background: #31363b;\n"
"    border: 1px solid #403F3F;\n"
"    titlebar-close-icon: url(:/qss_icons/rc/close.png);\n"
"    titlebar-normal-icon: url(:/qss_icons/rc/undock.png);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button {\n"
"    border: 1px solid transparent;\n"
"    border-radius: 2px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover {\n"
"    background: rgba(255, 255, 255, 10);\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed {\n"
"    padding: 1px -1px -1px 1px;\n"
"    background: rgba(255, 255, 255, 10);\n"
"}\n"
"\n"
"QTreeView, QListView\n"
"{\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"QTreeView:branch:selected, QTreeView:branch:hover\n"
"{\n"
"    background: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"    border-image: url(:/qss_icons/rc/transparent.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    image: url(:/qss_icons/rc/branch_closed.png);\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"    image: url(:/qss_icons/rc/branch_open.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed:hover,\n"
"QTreeView::branch:closed:has-children:has-siblings:hover {\n"
"    image: url(:/qss_icons/rc/branch_closed-on.png);\n"
"    }\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings:hover,\n"
"QTreeView::branch:open:has-children:has-siblings:hover  {\n"
"    image: url(:/qss_icons/rc/branch_open-on.png);\n"
"    }\n"
"\n"
"QListView::item:!selected:hover, QTreeView::item:!selected:hover  {\n"
"    background: rgba(167,218,245, 0.3);\n"
"    outline: 0;\n"
"    color: #eff0f1\n"
"}\n"
"\n"
"QListView::item:selected:hover, QTreeView::item:selected:hover  {\n"
"    background: #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #565a5e;\n"
"    height: 4px;\n"
"    background: #565a5e;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #232629;\n"
"    border: 1px solid #565a5e;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: -8px 0;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #565a5e;\n"
"    width: 4px;\n"
"    background: #565a5e;\n"
"    margin: 0px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #232629;\n"
"    border: 1px solid #565a5e;\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin: 0 -8px;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"    border: 1px transparent #76797C;\n"
"    border-radius: 2px;\n"
"    margin: 3px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] { /* only for MenuButtonPopup */\n"
" padding-right: 20px; /* make way for the popup button */\n"
" border: 1px #76797C;\n"
" border-radius: 5px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] { /* only for InstantPopup */\n"
" padding-right: 10px; /* make way for the popup button */\n"
" border: 1px #76797C;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover, QToolButton::menu-button:hover {\n"
"    background-color: transparent;\n"
"    border: 1px solid #3daee9;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed,\n"
"        QToolButton::menu-button:pressed {\n"
"    background-color: #3daee9;\n"
"    border: 1px solid #3daee9;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* the subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"QToolButton::menu-indicator {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"    top: -7px; left: -2px; /* shift it a bit */\n"
"}\n"
"\n"
"/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"QToolButton::menu-button {\n"
"    border: 1px transparent #76797C;\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    /* 16px width + 4px for border = 20px allocated above */\n"
"    width: 16px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QToolButton::menu-arrow:open {\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QPushButton::menu-indicator  {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    left: 8px;\n"
"}\n"
"\n"
"QTableView\n"
"{\n"
"    border: 1px solid #76797C;\n"
"    gridline-color: #31363b;\n"
"    background-color: #232629;\n"
"}\n"
"\n"
"\n"
"QTableView, QHeaderView\n"
"{\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTableView::item:pressed, QListView::item:pressed, QTreeView::item:pressed  {\n"
"    background: #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QTableView::item:selected:active, QTreeView::item:selected:active, QListView::item:selected:active  {\n"
"    background: #3daee9;\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"\n"
"QHeaderView\n"
"{\n"
"    background-color: #31363b;\n"
"    border: 1px transparent;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"\n"
"}\n"
"\n"
"QHeaderView::section  {\n"
"    background-color: #31363b;\n"
"    color: #eff0f1;\n"
"    padding: 5px;\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first, QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: transparent;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #76797C;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: transparent;\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
" {\n"
"    color: white;\n"
"    background-color: #334e5e;\n"
" }\n"
"\n"
" /* style the sort indicator */\n"
"QHeaderView::down-arrow {\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(:/qss_icons/rc/up_arrow.png);\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #31363b;\n"
"    border: 1px transparent #76797C;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QToolBox  {\n"
"    padding: 5px;\n"
"    border: 1px transparent black;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"    color: #eff0f1;\n"
"    background-color: #31363b;\n"
"    border: 1px solid #76797C;\n"
"    border-bottom: 1px transparent #31363b;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    font: italic;\n"
"    background-color: #31363b;\n"
"    border-color: #3daee9;\n"
" }\n"
"\n"
"QStatusBar::item {\n"
"    border: 0px transparent dark;\n"
" }\n"
"\n"
"\n"
"QFrame[height=\"3\"], QFrame[width=\"3\"] {\n"
"    background-color: #76797C;\n"
"}\n"
"\n"
"\n"
"QSplitter::handle {\n"
"    border: 1px dashed #76797C;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #787876;\n"
"    border: 1px solid #76797C;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    width: 1px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    height: 1px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 1px solid #76797C;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #05B8CC;\n"
"}\n"
"\n"
"QDateEdit\n"
"{\n"
"    selection-background-color: #3daee9;\n"
"    border-style: solid;\n"
"    border: 1px solid #3375A3;\n"
"    border-radius: 2px;\n"
"    padding: 1px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QDateEdit:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView\n"
"{\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #3375A3;\n"
"    selection-background-color: #3daee9;\n"
"}\n"
"\n"
"QDateEdit::drop-down\n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on, QDateEdit::down-arrow:hover,\n"
"QDateEdit::down-arrow:focus\n"
"{\n"
"    image: url(:/qss_icons/rc/down_arrow.png);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_left_frame.setMaximumSize(QtCore.QSize(700, 16777215))
        self.main_left_frame.setStyleSheet("border: none;")
        self.main_left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_left_frame.setObjectName("main_left_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_left_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.main_left_frame)
        self.frame_5.setEnabled(True)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_1 = QtWidgets.QFrame(self.frame_5)
        self.frame_1.setMinimumSize(QtCore.QSize(491, 0))
        self.frame_1.setStyleSheet("border: none;")
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Maincamera = QtWidgets.QLabel(self.frame_1)
        self.Maincamera.setStyleSheet("border: 1px solid #76797C;")
        self.Maincamera.setAlignment(QtCore.Qt.AlignCenter)
        self.Maincamera.setObjectName("Maincamera")
        self.horizontalLayout_2.addWidget(self.Maincamera)
        self.verticalLayout_5.addWidget(self.frame_1)
        self.GripperCamera = QtWidgets.QLabel(self.frame_5)
        self.GripperCamera.setStyleSheet("border: 1px solid #76797C;")
        self.GripperCamera.setAlignment(QtCore.Qt.AlignCenter)
        self.GripperCamera.setObjectName("GripperCamera")
        self.verticalLayout_5.addWidget(self.GripperCamera)
        self.verticalLayout.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.main_left_frame)
        self.main_right_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_right_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.main_right_frame.setStyleSheet("border: none;")
        self.main_right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_right_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_right_frame.setObjectName("main_right_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.main_right_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_17 = QtWidgets.QFrame(self.main_right_frame)
        self.frame_17.setStyleSheet("border: 1px solid #76797C;\n"
"")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setLineWidth(2)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_17)
        self.label_7.setLineWidth(0)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/qss_icons/icons/grapper-open.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_17)
        self.label_8.setLineWidth(0)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/qss_icons/icons/grapper-close.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setIndent(0)
        self.label_8.setOpenExternalLinks(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_17, 2, 3, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.main_right_frame)
        self.frame_11.setStyleSheet("border: 1px solid #76797C;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.analog_widget = AnalogGaugeWidget(self.frame_11)
        self.analog_widget.setStyleSheet("border: none;")
        self.analog_widget.setObjectName("analog_widget")
        self.verticalLayout_9.addWidget(self.analog_widget)
        self.gridLayout.addWidget(self.frame_11, 2, 2, 1, 1)
        self.indicators_3 = QtWidgets.QFrame(self.main_right_frame)
        self.indicators_3.setStyleSheet("border: 1px solid #76797C;")
        self.indicators_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.indicators_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.indicators_3.setObjectName("indicators_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.indicators_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gyro = QtWidgets.QLabel(self.indicators_3)
        self.gyro.setStyleSheet("border: none;")
        self.gyro.setAlignment(QtCore.Qt.AlignCenter)
        self.gyro.setObjectName("gyro")
        self.gridLayout_4.addWidget(self.gyro, 2, 0, 1, 1)
        self.temp = QtWidgets.QLabel(self.indicators_3)
        self.temp.setStyleSheet("border: none;")
        self.temp.setAlignment(QtCore.Qt.AlignCenter)
        self.temp.setObjectName("temp")
        self.gridLayout_4.addWidget(self.temp, 0, 0, 1, 1)
        self.acce = QtWidgets.QLabel(self.indicators_3)
        self.acce.setStyleSheet("border: none;")
        self.acce.setAlignment(QtCore.Qt.AlignCenter)
        self.acce.setObjectName("acce")
        self.gridLayout_4.addWidget(self.acce, 1, 0, 1, 1)
        self.vAcce = QtWidgets.QLabel(self.indicators_3)
        self.vAcce.setText("")
        self.vAcce.setObjectName("vAcce")
        self.gridLayout_4.addWidget(self.vAcce, 1, 1, 1, 1)
        self.vTemp = QtWidgets.QLabel(self.indicators_3)
        self.vTemp.setText("")
        self.vTemp.setObjectName("vTemp")
        self.gridLayout_4.addWidget(self.vTemp, 0, 1, 1, 1)
        self.vBar30 = QtWidgets.QLabel(self.indicators_3)
        self.vBar30.setText("")
        self.vBar30.setObjectName("vBar30")
        self.gridLayout_4.addWidget(self.vBar30, 3, 1, 1, 1)
        self.vGyro = QtWidgets.QLabel(self.indicators_3)
        self.vGyro.setText("")
        self.vGyro.setObjectName("vGyro")
        self.gridLayout_4.addWidget(self.vGyro, 2, 1, 1, 1)
        self.bar30 = QtWidgets.QLabel(self.indicators_3)
        self.bar30.setStyleSheet("border: none;")
        self.bar30.setAlignment(QtCore.Qt.AlignCenter)
        self.bar30.setObjectName("bar30")
        self.gridLayout_4.addWidget(self.bar30, 3, 0, 1, 1)
        self.bar30.raise_()
        self.gyro.raise_()
        self.acce.raise_()
        self.vTemp.raise_()
        self.vAcce.raise_()
        self.vGyro.raise_()
        self.vBar30.raise_()
        self.temp.raise_()
        self.gridLayout.addWidget(self.indicators_3, 2, 4, 1, 1)
        self.indicators_1 = QtWidgets.QFrame(self.main_right_frame)
        self.indicators_1.setStyleSheet("border: 1px solid #76797C;")
        self.indicators_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.indicators_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.indicators_1.setObjectName("indicators_1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.indicators_1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cam1 = QtWidgets.QLabel(self.indicators_1)
        self.cam1.setStyleSheet("border: none;")
        self.cam1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam1.setObjectName("cam1")
        self.verticalLayout_10.addWidget(self.cam1)
        self.cam2 = QtWidgets.QLabel(self.indicators_1)
        self.cam2.setStyleSheet("border: none;")
        self.cam2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam2.setObjectName("cam2")
        self.verticalLayout_10.addWidget(self.cam2)
        self.Jetson = QtWidgets.QLabel(self.indicators_1)
        self.Jetson.setStyleSheet("border: none;")
        self.Jetson.setAlignment(QtCore.Qt.AlignCenter)
        self.Jetson.setObjectName("Jetson")
        self.verticalLayout_10.addWidget(self.Jetson)
        self.Pixhawk = QtWidgets.QLabel(self.indicators_1)
        self.Pixhawk.setStyleSheet("border: none;")
        self.Pixhawk.setAlignment(QtCore.Qt.AlignCenter)
        self.Pixhawk.setObjectName("Pixhawk")
        self.verticalLayout_10.addWidget(self.Pixhawk)
        self.gridLayout.addWidget(self.indicators_1, 0, 4, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.main_right_frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("border: 1px solid #76797C;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setStyleSheet("border: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.timerLabel = QtWidgets.QLabel(self.frame_3)
        self.timerLabel.setStyleSheet("border: none;")
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setObjectName("timerLabel")
        self.verticalLayout_4.addWidget(self.timerLabel)
        self.startButton = QtWidgets.QPushButton(self.frame_3)
        self.startButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #42ba32;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: #a6a6a6;\n"
"    border-width: 1px;\n"
"    border-color: #454545;\n"
"    border-style: solid;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 2px;\n"
"    color: #454545;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    background-color: #4edb3b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #42ba32;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_4.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.frame_3)
        self.stopButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #ba3232;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: #a6a6a6;\n"
"    border-width: 1px;\n"
"    border-color: #454545;\n"
"    border-style: solid;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 2px;\n"
"    color: #454545;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    background-color: #db3b3b;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #ba3232;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}")
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout_4.addWidget(self.stopButton)
        self.resetButton = QtWidgets.QPushButton(self.frame_3)
        self.resetButton.setStyleSheet("\n"
"QPushButton\n"
"{\n"
"    color: #eff0f1;\n"
"    background-color: #9e9e9e;\n"
"    border-width: 1px;\n"
"    border-color: #76797C;\n"
"    border-style: solid;\n"
"    padding: 5px;\n"
"    border-radius: 2px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: #a6a6a6;\n"
"    border-width: 1px;\n"
"    border-color: #454545;\n"
"    border-style: solid;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    border-radius: 2px;\n"
"    color: #454545;\n"
"}\n"
"\n"
"QPushButton:focus {\n"
"    background-color: #bababa ;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: #dbdbdb;\n"
"    padding-top: -15px;\n"
"    padding-bottom: -17px;\n"
"}")
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_4.addWidget(self.resetButton)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.main_right_frame)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_7.setStyleSheet("border: none;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_13 = QtWidgets.QFrame(self.frame_7)
        self.frame_13.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_13.setStyleSheet("border: 1px solid #76797C;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backward = QtWidgets.QLabel(self.frame_13)
        self.backward.setAutoFillBackground(False)
        self.backward.setLineWidth(0)
        self.backward.setText("")
        self.backward.setPixmap(QtGui.QPixmap(":/qss_icons/icons/bckwrd-arrow.png"))
        self.backward.setScaledContents(True)
        self.backward.setWordWrap(True)
        self.backward.setObjectName("backward")
        self.gridLayout_2.addWidget(self.backward, 3, 1, 1, 1)
        self.forward = QtWidgets.QLabel(self.frame_13)
        self.forward.setLineWidth(0)
        self.forward.setText("")
        self.forward.setPixmap(QtGui.QPixmap("qss_icons/icons/frwrd-arrow.png"))
        self.forward.setScaledContents(True)
        self.forward.setWordWrap(True)
        self.forward.setObjectName("forwardBtn")
        self.gridLayout_2.addWidget(self.forward, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_13)
        self.label_3.setLineWidth(0)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/qss_icons/icons/left-arrow.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_13)
        self.pushButton_9.setEnabled(False)
        self.pushButton_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("border: none;\n"
"font: 15px;\n"
"color: #ffffff;\n"
"background-color: #9e9e9e;\n"
"  border: 2px solid #9e9e9e;\n"
"  border-radius: 16px;")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 2, 1, 1, 1)
        self.rightBtn = QtWidgets.QLabel(self.frame_13)
        self.rightBtn.setLineWidth(0)
        self.rightBtn.setText("")
        self.rightBtn.setPixmap(QtGui.QPixmap(":/qss_icons/icons/right-arrow.png"))
        self.rightBtn.setScaledContents(True)
        self.rightBtn.setWordWrap(True)
        self.rightBtn.setIndent(-1)
        self.rightBtn.setObjectName("rightBtn")
        self.gridLayout_2.addWidget(self.rightBtn, 2, 2, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.frame_7)
        self.frame_12.setStyleSheet("border: 1px solid #76797C;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_12)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/qss_icons/icons/cw.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_12)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/qss_icons/icons/upward-arrow.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setIndent(0)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/qss_icons/icons/downward-arrow.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_12)
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/qss_icons/icons/ccw.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setIndent(0)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_3.addWidget(self.frame_12)
        self.gridLayout.addWidget(self.frame_7, 8, 2, 1, 3)
        self.indicators_2 = QtWidgets.QFrame(self.main_right_frame)
        self.indicators_2.setStyleSheet("border: 1px solid #76797C;")
        self.indicators_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.indicators_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.indicators_2.setObjectName("indicators_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.indicators_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.thrusters_indicators = QtWidgets.QLabel(self.indicators_2)
        self.thrusters_indicators.setStyleSheet("border: none;")
        self.thrusters_indicators.setAlignment(QtCore.Qt.AlignCenter)
        self.thrusters_indicators.setObjectName("thrusters_indicators")
        self.horizontalLayout_4.addWidget(self.thrusters_indicators)
        self.frame_16 = QtWidgets.QFrame(self.indicators_2)
        self.frame_16.setStyleSheet("border: none;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frnt_lft = QtWidgets.QLabel(self.frame_16)
        self.frnt_lft.setAlignment(QtCore.Qt.AlignCenter)
        self.frnt_lft.setObjectName("frnt_lft")
        self.gridLayout_3.addWidget(self.frnt_lft, 0, 0, 1, 1)
        self.mid_lft = QtWidgets.QLabel(self.frame_16)
        self.mid_lft.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_lft.setObjectName("mid_lft")
        self.gridLayout_3.addWidget(self.mid_lft, 1, 0, 1, 1)
        self.frnt_rght = QtWidgets.QLabel(self.frame_16)
        self.frnt_rght.setAlignment(QtCore.Qt.AlignCenter)
        self.frnt_rght.setObjectName("frnt_rght")
        self.gridLayout_3.addWidget(self.frnt_rght, 0, 1, 1, 1)
        self.bck_lft = QtWidgets.QLabel(self.frame_16)
        self.bck_lft.setAlignment(QtCore.Qt.AlignCenter)
        self.bck_lft.setObjectName("bck_lft")
        self.gridLayout_3.addWidget(self.bck_lft, 2, 0, 1, 1)
        self.mid_rght = QtWidgets.QLabel(self.frame_16)
        self.mid_rght.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_rght.setObjectName("mid_rght")
        self.gridLayout_3.addWidget(self.mid_rght, 1, 1, 1, 1)
        self.bck_rght = QtWidgets.QLabel(self.frame_16)
        self.bck_rght.setAlignment(QtCore.Qt.AlignCenter)
        self.bck_rght.setObjectName("bck_rght")
        self.gridLayout_3.addWidget(self.bck_rght, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_16)
        self.gridLayout.addWidget(self.indicators_2, 0, 3, 1, 1)
        self.horizontalLayout.addWidget(self.main_right_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 31))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuChange_Camera_Location = QtWidgets.QMenu(self.menufile)
        self.menuChange_Camera_Location.setObjectName("menuChange_Camera_Location")
        self.menuIndecators = QtWidgets.QMenu(self.menufile)
        self.menuIndecators.setObjectName("menuIndecators")
        self.menuThrusters = QtWidgets.QMenu(self.menufile)
        self.menuThrusters.setObjectName("menuThrusters")
        self.menuabout = QtWidgets.QMenu(self.menubar)
        self.menuabout.setObjectName("menuabout")
        self.menuAutonomous = QtWidgets.QMenu(self.menubar)
        self.menuAutonomous.setObjectName("menuAutonomous")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionchange_camera_location = QtWidgets.QAction(MainWindow)
        self.actionchange_camera_location.setObjectName("actionchange_camera_location")
        self.actionRestart_CAM_1 = QtWidgets.QAction(MainWindow)
        self.actionRestart_CAM_1.setObjectName("actionRestart_CAM_1")
        self.actionRestart_CAM_2 = QtWidgets.QAction(MainWindow)
        self.actionRestart_CAM_2.setObjectName("actionRestart_CAM_2")
        self.actionshourtcuts = QtWidgets.QAction(MainWindow)
        self.actionshourtcuts.setObjectName("actionshourtcuts")
        self.actionRestart_Jetson = QtWidgets.QAction(MainWindow)
        self.actionRestart_Jetson.setObjectName("actionRestart_Jetson")
        self.actionRestart_Pixhawk = QtWidgets.QAction(MainWindow)
        self.actionRestart_Pixhawk.setObjectName("actionRestart_Pixhawk")
        self.actionChange_Thruster_1_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_1_direction.setObjectName("actionChange_Thruster_1_direction")
        self.actionChange_Thruster_2_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_2_direction.setObjectName("actionChange_Thruster_2_direction")
        self.actionChange_Thruster_3_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_3_direction.setObjectName("actionChange_Thruster_3_direction")
        self.actionChange_Thruster_4_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_4_direction.setObjectName("actionChange_Thruster_4_direction")
        self.actionChange_Thruster_5_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_5_direction.setObjectName("actionChange_Thruster_5_direction")
        self.actionChange_Thruster_6_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_Thruster_6_direction.setObjectName("actionChange_Thruster_6_direction")
        self.actionChange_all_Thrusters_direction = QtWidgets.QAction(MainWindow)
        self.actionChange_all_Thrusters_direction.setObjectName("actionChange_all_Thrusters_direction")
        self.actionReset_to_defualt = QtWidgets.QAction(MainWindow)
        self.actionReset_to_defualt.setObjectName("actionReset_to_defualt")
        self.actionDepth_Hold = QtWidgets.QAction(MainWindow)
        self.actionDepth_Hold.setObjectName("actionDepth_Hold")
        self.actionforward = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("qss_icons/icons/frwrd-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionforward.setIcon(icon)
        self.actionforward.setObjectName("actionforward")
        self.menuChange_Camera_Location.addAction(self.actionchange_camera_location)
        self.menuChange_Camera_Location.addAction(self.actionRestart_CAM_1)
        self.menuChange_Camera_Location.addAction(self.actionRestart_CAM_2)
        self.menuIndecators.addAction(self.actionRestart_Jetson)
        self.menuIndecators.addAction(self.actionRestart_Pixhawk)
        self.menuThrusters.addAction(self.actionChange_Thruster_1_direction)
        self.menuThrusters.addAction(self.actionChange_Thruster_2_direction)
        self.menuThrusters.addAction(self.actionChange_Thruster_3_direction)
        self.menuThrusters.addAction(self.actionChange_Thruster_4_direction)
        self.menuThrusters.addAction(self.actionChange_Thruster_5_direction)
        self.menuThrusters.addAction(self.actionChange_Thruster_6_direction)
        self.menuThrusters.addAction(self.actionChange_all_Thrusters_direction)
        self.menuThrusters.addAction(self.actionReset_to_defualt)
        self.menufile.addAction(self.menuChange_Camera_Location.menuAction())
        self.menufile.addAction(self.menuIndecators.menuAction())
        self.menufile.addAction(self.menuThrusters.menuAction())
        self.menuabout.addAction(self.actionshourtcuts)
        self.menuAutonomous.addAction(self.actionDepth_Hold)
        self.menubar.addAction(self.menuAutonomous.menuAction())
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuabout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pilot"))
        self.Maincamera.setText(_translate("MainWindow", "Main Camera"))
        self.GripperCamera.setText(_translate("MainWindow", "Gripper Camera"))
        self.gyro.setText(_translate("MainWindow", "Gyro"))
        self.temp.setText(_translate("MainWindow", "T"))
        self.acce.setText(_translate("MainWindow", "Acc"))
        self.bar30.setText(_translate("MainWindow", "Bar30"))
        self.cam1.setText(_translate("MainWindow", "Camera 1"))
        self.cam2.setText(_translate("MainWindow", "Camera 2"))
        self.Jetson.setText(_translate("MainWindow", "Jetson"))
        self.Pixhawk.setText(_translate("MainWindow", "Pixhawk"))
        self.timerLabel.setText(_translate("MainWindow", "00:00"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.backward.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/bckwrd-arrow.png\"/></p></body></html>"))
        self.backward.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/bckwrd-arrow.png\"/></p></body></html>"))
        self.forward.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/frwrd-arrow.png\"/></p></body></html>"))
        self.forward.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/frwrd-arrow.png\"/></p></body></html>"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/left-arrow.png\"/></p></body></html>"))
        self.label_3.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/left-arrow.png\"/></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "STATE"))
        self.rightBtn.setToolTip(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/right-arrow.png\"/></p></body></html>"))
        self.rightBtn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/right-arrow.png\"/></p></body></html>"))
        self.label.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/cw.png\"/></p></body></html>"))
        self.label_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/upward-arrow.png\"/></p></body></html>"))
        self.label_5.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/downward-arrow.png\"/></p></body></html>"))
        self.label_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><img src=\":/qss_icons/icons/ccw.png\"/></p></body></html>"))
        self.thrusters_indicators.setText(_translate("MainWindow", "Thrusters"))
        self.frnt_lft.setText(_translate("MainWindow", "O"))
        self.mid_lft.setText(_translate("MainWindow", "O"))
        self.frnt_rght.setText(_translate("MainWindow", "O"))
        self.bck_lft.setText(_translate("MainWindow", "O"))
        self.mid_rght.setText(_translate("MainWindow", "O"))
        self.bck_rght.setText(_translate("MainWindow", "O"))
        self.menufile.setTitle(_translate("MainWindow", "options"))
        self.menuChange_Camera_Location.setTitle(_translate("MainWindow", "Camera"))
        self.menuIndecators.setTitle(_translate("MainWindow", "Indicators"))
        self.menuThrusters.setTitle(_translate("MainWindow", "Thrusters"))
        self.menuabout.setTitle(_translate("MainWindow", "about"))
        self.menuAutonomous.setTitle(_translate("MainWindow", "Autonomous mode"))
        self.actionchange_camera_location.setText(_translate("MainWindow", "Change Camera Location"))
        self.actionRestart_CAM_1.setText(_translate("MainWindow", "Restart CAM 1"))
        self.actionRestart_CAM_2.setText(_translate("MainWindow", "Restart CAM 2"))
        self.actionshourtcuts.setText(_translate("MainWindow", "Shourtcuts"))
        self.actionRestart_Jetson.setText(_translate("MainWindow", "Restart Jetson"))
        self.actionRestart_Pixhawk.setText(_translate("MainWindow", "Restart Pixhawk"))
        self.actionChange_Thruster_1_direction.setText(_translate("MainWindow", "Change Thruster front-right direction"))
        self.actionChange_Thruster_2_direction.setText(_translate("MainWindow", "Change Thruster front-left direction"))
        self.actionChange_Thruster_3_direction.setText(_translate("MainWindow", "Change Thruster mid-right direction"))
        self.actionChange_Thruster_4_direction.setText(_translate("MainWindow", "Change Thruster mid-left direction"))
        self.actionChange_Thruster_5_direction.setText(_translate("MainWindow", "Change Thruster back-right direction"))
        self.actionChange_Thruster_6_direction.setText(_translate("MainWindow", "Change Thruster back-left direction"))
        self.actionChange_all_Thrusters_direction.setText(_translate("MainWindow", "Change all Thrusters direction"))
        self.actionReset_to_defualt.setText(_translate("MainWindow", "Reset to defualt"))
        self.actionDepth_Hold.setText(_translate("MainWindow", "Depth Hold"))
        self.actionforward.setText(_translate("MainWindow", "forward"))
from analoggaugewidget import AnalogGaugeWidget



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
